apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api
  namespace: k8s  # Namespace should match the MongoDB namespace
  labels: 
    role: api
    env: demo
spec: 
  replicas: 2
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector: 
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: backend
        image: manusuresh126/backendapp:latest
        env:
          - name: MONGO_CONN_STR
            value: mongodb://mongodb-service:27017/todo?directConnection=true  # Service name matches MongoDB service
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret  # Matches your MongoDB secret name
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret  # Matches your MongoDB secret name
                key: password
        ports:
        - containerPort: 3500
        livenessProbe: 
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
      imagePullSecrets:
      - name: my-dockerhub-secret  # Ensure this Docker registry secret exists
