apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcp-pvc
  namespace: k8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: pd-standard
