apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: k8s  # Change this if your secret needs to be in a different namespace
type: Opaque
data:
  username: YWRtaW4K
  password: QXZheWFAMTIzCg==
